#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate hand-FASM for an N-bit visible-blink at LAB(4,18)+LAB(4,17).

Silicon-validated 2026-05-03 night:
  * W=17 LED solid-on at 763 Hz (above flicker fusion).
  * W=23 LED 6 Hz visible blink.

Both validated via the codec stack: arith_blockband_by_width.json's
multi_lab[16+N] entries, paired_carry_input validator mode, fasm2rbf's
LUT_ARITH_MULTI_LAB AND-clear semantics for v4-blob overflow cells.

Constraints (per CLAUDE.md + arith_blockband_by_width.json):
  - Multi-LAB carry chain blob mined ONLY at LAB(4,18) (full 16 LEs)
    + LAB(4,17) (1..16 LE spillover) — position-independence NOT proven.
  - Widths 17..32 use `LUT_ARITH_MULTI_LAB WIDTH=N`.
  - Chain bit i ↔ LAB(4,18) LE i for i<16, LAB(4,17) LE (i-16) for i≥16.
  - LE k corresponds to our_N = 2*k.
  - MSB is at LAB(4,17) LE (W-17) → our_N = 2*(W-17).
  - For OUTROUTE_G15 to be pinnable, MSB our_N must be EVEN multiple of 4
    (= Q-N even, LCCOMB-pinnable).  → W-17 must be EVEN.  Valid widths
    (with even MSB-LE): 17, 19, 21, 23, 25, 27, 29, 31.

Usage:
    python3 scripts/visible_blink/gen_visible_blink_fasm.py W output.fasm

Examples:
    python3 scripts/visible_blink/gen_visible_blink_fasm.py 17 tmp/visible_blink/visible_blink_W17.fasm
    python3 scripts/visible_blink/gen_visible_blink_fasm.py 23 tmp/visible_blink/visible_blink_W23.fasm
"""
import sys
from pathlib import Path

VALID_WIDTHS = [17, 19, 21, 23, 25, 27, 29, 31]


def gen(width: int) -> str:
    if width < 17 or width > 32:
        raise ValueError(f"width {width} out of range [17, 32]")
    spillover = width - 16  # bits at LAB(4,17), 1..16
    msb_le = spillover - 1  # LE index in LAB(4,17), 0..15
    msb_n = 2 * msb_le      # our_N
    msb_qn = msb_n // 2     # Quartus N
    if msb_qn % 2 != 0:
        # Odd Q-N → not LCCOMB-pinnable → can't mine OUTROUTE here
        # (would need LCFF mining path)
        raise ValueError(
            f"width {width}: MSB at our_N={msb_n} (Q-N={msb_qn}) is odd, "
            f"OUTROUTE_G15 mining via LCCOMB syntax fails. "
            f"Valid widths with even MSB Q-N: {VALID_WIDTHS}"
        )

    blink_hz = 50_000_000 / (1 << (width - 1))
    lines = [
        f"# {width}-bit visible-blink hand-FASM (auto-generated by gen_visible_blink_fasm.py)",
        f"# Chain placement: LAB(4,18) bits 0..15, LAB(4,17) bits 16..{width-1} (LE 0..{msb_le})",
        f"# MSB position: X4Y17N{msb_n} (Q-N={msb_qn}); blink ~{blink_hz:.2f} Hz @ 50 MHz",
        f"# Requires: OUTROUTE_G15 X4Y17N{msb_n} pre-mined in results/output_route_sigcache.json",
        "IOB_PAD_NV",
        "GCLK_PIN PIN_E1",
        "IOB_CLK_INPUT PIN_E1",
        "",
        "# LAB(4,18) — bits 0..15 (full LAB)",
    ]
    # LAB(4,18): all 16 LEs at our_N = 0,2,4,...,30
    for n in range(0, 32, 2):
        lines.append(f"X4Y18N{n}.LUT_ARITH = 0x0000")
        lines.append(f"X4Y18N{n}.DFF")
    lines.append(f"")
    lines.append(f"# LAB(4,17) — bits 16..{width-1} ({spillover} LEs, MSB at N={msb_n})")
    # LAB(4,17): LEs 0..msb_le at our_N = 0,2,...,msb_n
    for n in range(0, msb_n + 1, 2):
        lines.append(f"X4Y17N{n}.LUT_ARITH = 0x0000")
        lines.append(f"X4Y17N{n}.DFF")
    lines.append("")
    lines.append(f"# Carry-chain block-band activation (full + {spillover}-bit spillover)")
    lines.append(f"LUT_ARITH_MULTI_LAB WIDTH={width}")
    lines.append("")
    lines.append("# Per-LAB clock activation")
    lines.append("LAB_CLK_SEL X4Y18")
    lines.append("LAB_CLK_SEL X4Y17")
    lines.append("")
    lines.append("# NO LAB_CLK_SEL_LE directives: arith-mode LEs inherit clocking from")
    lines.append("# LAB-level LAB_CLK_SEL alone.  The LAB_CLK_SEL_LE codec over-emits")
    lines.append("# 20-35 cells per LE that Quartus c_ml gold doesn't set — at W≥18 the")
    lines.append("# accumulated noise poisons chain control bits and the chain saturates.")
    lines.append("# Silicon-validated W=23 V6 baseline has zero LAB_CLK_SEL_LE.  See memory")
    lines.append("# `multi_lab_carry_silicon_validated_2026_05_03`.")
    lines.append("")
    lines.append(f"# MSB → G15 output")
    lines.append(f"OUTROUTE_G15 X4Y17N{msb_n}")
    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    width = int(sys.argv[1])
    out_path = Path(sys.argv[2])
    fasm = gen(width)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(fasm)
    print(f"Wrote {out_path} ({len(fasm.splitlines())} lines, W={width})")


if __name__ == "__main__":
    main()
