# SPDX-License-Identifier: GPL-3.0-or-later
"""Convert a Quartus-produced RBF into a pure BIT-directive FASM file.

Use when the open toolchain's ROUTE directive cannot produce a silicon-
functional bitstream for a design (e.g., cross-LAB routes with broken
sig-cache entries, or NEORV32-scale designs nextpnr cannot route). Feed
the target design through Quartus to get a gold RBF, then run this tool
to produce an equivalent FASM file that fasm2rbf.py can re-materialize
byte-perfectly.

HW-validated 2026-04-22 (two_lab_gold_bits3.rbf) + 2026-04-23 (lits_pair
bit reconstruction): the round-trip Quartus RBF → BIT FASM → fasm2rbf
produces byte-identical, silicon-functional output.

Usage:
    python3 scripts/bit_workaround/quartus_gold_to_bit_fasm.py \\
        <gold.rbf> <out.fasm> [--base <baseline.rbf>]

    # then rebuild byte-identically:
    python3 fuzz/fasm2rbf.py <out.fasm> <baseline.rbf> <rebuilt.rbf>
    # verify:
    cmp <gold.rbf> <rebuilt.rbf>
"""
import argparse, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_BASE = ROOT / "results" / "rbf" / "nv_zero_global.rbf"


def diff_all(a: bytes, b: bytes):
    """Emit (off, bp) for every differing bit. No filtering — hdr, fabric,
    and CRC bits are all included so fasm2rbf's CRC patcher handles them
    correctly during round-trip."""
    out = []
    n = len(a)
    if n != len(b):
        raise ValueError(f"size mismatch: {n} vs {len(b)}")
    for i in range(n):
        x = a[i] ^ b[i]
        if not x:
            continue
        for bp in range(8):
            if x & (1 << bp):
                out.append((i, bp))
    return out


def main():
    p = argparse.ArgumentParser()
    p.add_argument("gold", type=Path, help="Quartus-produced .rbf (368 011 B)")
    p.add_argument("out", type=Path, help="output .fasm path")
    p.add_argument("--base", type=Path, default=DEFAULT_BASE,
                   help=f"baseline RBF (default: {DEFAULT_BASE})")
    a = p.parse_args()

    gold = a.gold.read_bytes()
    base = a.base.read_bytes()
    if len(gold) != 368011:
        sys.exit(f"gold size {len(gold)} != 368011 — not a valid EP4CE6 RBF")
    if len(base) != 368011:
        sys.exit(f"base size {len(base)} != 368011")

    cells = diff_all(base, gold)

    # Categorize for the header comment only (informational).
    hdr = sum(1 for o, b in cells if (o - 32) // 210 < 25)
    crc = sum(1 for o, b in cells if (o - 32) // 210 >= 25
              and (o - 32) % 210 >= 208)
    fab = len(cells) - hdr - crc

    lines = [
        f"# Auto-generated by quartus_gold_to_bit_fasm.py",
        f"# source: {a.gold.name}  ({len(gold)} B)",
        f"# base:   {a.base.name}  ({len(base)} B)",
        f"# cells:  {len(cells)} total  ({hdr} hdr, {fab} fab, {crc} crc)",
        "",
    ]
    lines.extend(f"BIT {off} {bp}" for off, bp in cells)
    a.out.write_text("\n".join(lines) + "\n")
    print(f"wrote {a.out}  ({len(cells)} BIT directives: "
          f"{hdr} hdr + {fab} fab + {crc} crc)")
    print(f"rebuild with: python3 fuzz/fasm2rbf.py {a.out} {a.base} <rebuilt.rbf>")


if __name__ == "__main__":
    main()
