# SPDX-License-Identifier: GPL-3.0-or-later
"""Hybrid ζ + DESIGN_BLOCK_BAND_PACK extraction.

Like quartus_gold_to_bit_fasm.py but emits cells in the block-band
region (frames 1692-1738, byte<208) via the `DESIGN_BLOCK_BAND_PACK
<tag>` directive instead of inline BIT directives.  Used to validate
that DESIGN_BLOCK_BAND_PACK encodes the M9K mode bits silicon-correctly:

  1. Mine the design's block-band into results/design_block_band.json.
  2. Run this tool with the same design's RBF + the same tag.
  3. Run fasm2rbf on the output.  If byte-identical to the input RBF,
     the directive correctly substitutes for those BIT directives.
  4. Flash.  Silicon equivalence to the original RBF proves the
     DESIGN_BLOCK_BAND_PACK round-trip is silicon-correct.

This is the silicon Step F gate for Option 3-residual.

Usage:
    # 1. Mine pack
    python3 scripts/mine_design_block_band.py --tag <T> --rbf <gold.rbf>

    # 2. Hybrid extract
    python3 scripts/bit_workaround/zeta_with_design_pack.py \\
        <gold.rbf> <out.fasm> --tag <T>

    # 3. Rebuild + compare
    python3 fuzz/fasm2rbf.py <out.fasm> <baseline.rbf> <rebuilt.rbf>
    cmp <gold.rbf> <rebuilt.rbf>
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_BASE = ROOT / "results/rbf/nv_zero_global.rbf"

PRE = 32
FRAME = 210
BB_FRAME_LO = 1692
BB_FRAME_HI = 1738
DATA_BYTES = 208  # bytes 0..207 are data, 208/209 are CRC


def in_block_band(off: int) -> bool:
    """True iff off is in the block-band data-byte region the
    DESIGN_BLOCK_BAND_PACK directive owns."""
    if off < PRE:
        return False
    rel = off - PRE
    frame = rel // FRAME
    byte_in_frame = rel % FRAME
    return BB_FRAME_LO <= frame <= BB_FRAME_HI and byte_in_frame < DATA_BYTES


def diff_partition(base: bytes, gold: bytes) -> tuple[list, list]:
    """Return (block_band_cells, other_cells) — each list of (off, bp)."""
    if len(base) != len(gold):
        raise ValueError(f"size mismatch: {len(base)} vs {len(gold)}")
    bb: list[tuple[int, int]] = []
    other: list[tuple[int, int]] = []
    for i in range(len(base)):
        x = base[i] ^ gold[i]
        if not x:
            continue
        target = bb if in_block_band(i) else other
        for bp in range(8):
            if x & (1 << bp):
                target.append((i, bp))
    return bb, other


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("gold", type=Path, help="Quartus-produced .rbf")
    p.add_argument("out", type=Path, help="output .fasm path")
    p.add_argument("--tag", required=True,
                   help="design pack tag (must exist in design_block_band.json)")
    p.add_argument("--base", type=Path, default=DEFAULT_BASE,
                   help=f"baseline RBF (default: {DEFAULT_BASE})")
    args = p.parse_args()

    gold = args.gold.read_bytes()
    base = args.base.read_bytes()
    if len(gold) != 368011:
        sys.exit(f"gold size {len(gold)} != 368011")
    if len(base) != 368011:
        sys.exit(f"base size {len(base)} != 368011")

    bb_cells, other_cells = diff_partition(base, gold)

    # Sanity: bb_cells should match the design pack JSON exactly
    import json
    db = json.loads((ROOT / "results/design_block_band.json").read_text())
    if args.tag not in db:
        sys.exit(f"tag {args.tag!r} not in design_block_band.json — "
                 f"mine first via scripts/mine_design_block_band.py")
    pack_cells = {tuple(c) for c in db[args.tag]["cells"]}
    bb_set = set(bb_cells)
    if pack_cells != bb_set:
        diff = pack_cells.symmetric_difference(bb_set)
        sys.exit(f"design pack mismatch: {len(diff)} cells differ between "
                 f"design_block_band.json[{args.tag}] and gold-vs-base "
                 f"diff in block-band — re-mine the pack from this gold.rbf")

    lines = [
        f"# Auto-generated by zeta_with_design_pack.py",
        f"# source:    {args.gold.name}  ({len(gold)} B)",
        f"# base:      {args.base.name}  ({len(base)} B)",
        f"# pack-tag:  {args.tag}  ({len(bb_cells)} block-band cells)",
        f"# inline:    {len(other_cells)} BIT directives (non-block-band)",
        f"# total bits:{len(bb_cells) + len(other_cells)}",
        "",
        f"DESIGN_BLOCK_BAND_PACK {args.tag}",
    ]
    lines.extend(f"BIT {off} {bp}" for off, bp in other_cells)
    args.out.write_text("\n".join(lines) + "\n")
    print(f"  block-band cells (via pack): {len(bb_cells)}")
    print(f"  inline BIT directives:       {len(other_cells)}")
    print(f"  wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
